### PR TITLE
add food, improve formatting

### PR DESCRIPTION
**Pull request by Grimblewald**
added tip-top food
fixed things up from being one big line to many rows, which if legal, is better IMO

### CODE REVIEW

**Comment by PiiDish** [comment]
LGTM

**Review by PiiDish — COMMENTED** [review]
LGTM

**Review by PiiDish — DISMISSED** [review]
Great

**Comment by ysims** [comment]
You'll need to fix up the merge conflicts. Having the foods on separate lines is probably okay, since it should still create merge conflicts that people need to fix up.

**Comment by Grimblewald** [comment]
That should sort that out. That being said, the pending requests would throw conflicts if mine is accepted first. So in the interest of not shouldering others with extra work, if those could be merged first I'll be happy to fix my conflicts a final time thereafter.

**Review by Grimblewald — COMMENTED** [review]
looks good I think

**Pull request closed without merging**
