### PR TITLE
Added curry to Foods and Setting up Webots to NextTime

### PR DESCRIPTION
**Pull request by BaileyJoe**
added curry to Foods and 'Setting up Webots' to NextTime

### CODE REVIEW

**Comment by tayloryoung6396** [comment]
The title should be something like "Adds curry to food list". You also don't have to add your name

**Review by Happyman31 — DISMISSED** [review]
Nice! Looks good.

**Review by CMCD1998 — DISMISSED** [review]
butter chicken is the best

**Review by ysims — DISMISSED** [review]
LGTM

**Comment by ysims** [comment]
A PR has just been merged in, so you have new merge conflicts. Note that a change that has gone in also suggests Webots, so you'll want to make sure you're not suggesting something that's already there once you've merged :smile:

**Comment by ysims** [comment]
You might wanna update the PR title.

**Pull request closed without merging**
